DROP SEQUENCE HIBERNATE_SEQUENCE;

DROP TABLE kunde CASCADE CONSTRAINTS PURGE;
DROP TABLE lieferung CASCADE CONSTRAINTS PURGE;
DROP TABLE adresse CASCADE CONSTRAINTS PURGE;
DROP TABLE produkt CASCADE CONSTRAINTS PURGE;
DROP TABLE bestellung CASCADE CONSTRAINTS PURGE;
DROP TABLE bestellposition CASCADE CONSTRAINTS PURGE;
